version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  ml-disease-api:
    build: ./ml-models
    command: uvicorn disease_prediction.api:app --host 0.0.0.0 --port 8001
    volumes:
      - ./ml-models:/app
    ports:
      - "8001:8001"

  ml-xray-api:
    build: ./ml-models
    command: uvicorn xray_classification.api:app --host 0.0.0.0 --port 8002
    volumes:
      - ./ml-models:/app
    ports:
      - "8002:8002"

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: